name: fismatic
dependencies:
  - python>=3.5,<4
  - ipywidgets
  - jupyter
  - pandas
  - pip
  - pip:
      - autoflake
      - black
      - python-docx>0.8,<1
  - plotly=3
  - pytest
  - rope
  - spacy=3
